/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#ffade1',
        'outline': '#859399',
        'on-primary': '#003543',
        'inverse-surface': '#dde2f3',
        'on-secondary': '#450086',
        'surface': '#0e131f',
        'background': '#0e131f',
        'surface-container': '#1a202c',
        'primary-fixed': '#b7eaff',
        'on-secondary-fixed': '#290055',
        'on-primary-fixed-variant': '#004e60',
        'tertiary-fixed': '#ffd8ed',
        'surface-container-highest': '#2f3542',
        'inverse-primary': '#00677f',
        'secondary-fixed-dim': '#d8b9ff',
        'on-secondary-container': '#d5b5ff',
        'secondary-fixed': '#eddcff',
        'primary-fixed-dim': '#4cd6ff',
        'on-tertiary-fixed-variant': '#87006e',
        'on-error-container': '#ffdad6',
        'on-surface-variant': '#bbc9cf',
        'inverse-on-surface': '#2b303d',
        'secondary-container': '#6e06d0',
        'secondary': '#d8b9ff',
        'on-secondary-fixed-variant': '#6200bc',
        'surface-container-low': '#161c28',
        'surface-dim': '#0e131f',
        'on-tertiary-container': '#940079',
        'tertiary-container': '#ffa3df',
        'error-container': '#93000a',
        'on-primary-fixed': '#001f28',
        'surface-container-lowest': '#080e1a',
        'surface-bright': '#343946',
        'on-tertiary-fixed': '#3b002f',
        'outline-variant': '#3c494e',
        'on-surface': '#dde2f3',
        'on-tertiary': '#5f004d',
        'primary': '#a4e6ff',
        'surface-container-high': '#242a36',
        'on-background': '#dde2f3',
        'surface-variant': '#2f3542',
        'surface-tint': '#4cd6ff',
        'on-error': '#690005',
        'on-primary-container': '#00566a',
        'tertiary': '#ffceea',
        'primary-container': '#00d1ff',
        'error': '#ffb4ab',
        'brand-orange': '#FF8C00',
      },
      fontFamily: {
        'space-grotesk': ['Space Grotesk', 'sans-serif'],
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['72px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
